carpooling/routes/main_routes.py
"""
Main, user-facing routes for the application
"""
import secrets

from carpooling import db
from carpooling import mail
from carpooling.models import Address, Event, Carpool, User, Destination, \
    GeneratedCarpool, Organization
import logging
from carpooling.tasks import send_async_email
from carpooling.utils import driver_required
from flask import render_template, request, redirect, url_for, flash
import datetime
from flask_login import login_required, current_user, logout_user
from carpooling.utils import requires_auth_key
from flask_mail import Message
from flask import Blueprint, session
from carpooling import tasks_


main_blueprint = Blueprint('main', __name__, template_folder='templates')

DEFAULT_NUMBER_OF_CARPOOLS = 4

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)


# logFormatter = logging.Formatter(fmt=' %(name)s :: %(levelname)-8s :: %(message)s')
# logging.RootLogger(logging.DEBUG)


# h2 = logging.SMTPHandler(mailhost=app.config['MAIL_SERVER'],
#                             fromaddr=app.config['MAIL_USERNAME'],
#                             toaddrs=app.config['MAIL_USERNAME'],
#                             subject='Carpooling Error',
#                             credentials=(app.config['MAIL_USERNAME'],app.config['MAIL_PASSWORD']),
#                             secure=None)
# h2.setLevel(logging.CRITICAL)
# h2.setFormatter(logFormatter)
# logging.getLogger().addHandler(h2)


@main_blueprint.route('/')
def home_page(logout=False):
    """
    Home page. Also index page.
    """
    # if the user requested a logout, then they get logged out here
    logout = request.args.get('logout')
    if logout:
        logout_user()
        flash('You have been logged out.', 'message')
        logger.info(f'User {current_user} logged out')

    # finding the information needed for the dashboard... technically doesn't need to be done if not authenticated, but its not too bad
    events = Event.query.all()
    events = [event for event in events if event.date >=
              datetime.datetime.now() - datetime.timedelta(hours=36)]
    if current_user.is_authenticated:
        if current_user.num_seats is not None:
            driver_carpools = [carpool for carpool in Carpool.query.filter_by(driver_index=current_user.id).all(
            ) if carpool.event.date >= datetime.datetime.now() - datetime.timedelta(hours=36)]
        else:
            driver_carpools = []
        passenger_carpools = [carpool for carpool in current_user.passenger_carpools if carpool.event.date >=
                              datetime.datetime.now() - datetime.timedelta(hours=36)]
    else:
        driver_carpools = []
        passenger_carpools = []

    return render_template('index.html', user=current_user, driver_carpools=driver_carpools,
                           passenger_carpools=passenger_carpools, events=events)


@main_blueprint.route('/driver/<id>')
@requires_auth_key
def driver_page(id):
    """
    Driver page for passengers and other drivers to see
    last_name: last name of the driver
    first_name: first name of the driver
    """
    logger.info('driver page')
    try:
        driver = User.query.get(id)
    except:
        logger.info('no driver was found')
        return 'No driver was found.'

    logger.info('driver found')
    driver_info = {'lastname': driver.last_name.capitalize(),
                   'firstname': driver.first_name.capitalize(),
                   'car_type_1': driver.car_type_1,
                   'car_color_1': driver.car_color_1,
                   'car_type_2': driver.car_type_2,
                   'car_color_2': driver.car_color_2,
                   'number_seats': driver.num_seats,
                   'phone_number': driver.phone_number,
                   'email': driver.email_address,
                   'student_or_parent': driver.student_or_parent,
                   'emergencycontact': driver.emergency_contact_number,
                   'emergencycontactrelation': driver.emergency_contact_relation,
                   'licenseyears': driver.num_years_with_license,
                   'phone_number_string': f'tel:{driver.phone_number}',
                   'email_string': f'mailto:{driver.email_address}',
                   'extra_information': driver.extra_information}

    return render_template('driver_template.html', **driver_info, user=current_user)


@main_blueprint.route('/events')
def events_page():
    """
    Page to display all upcoming events. Probably should make an events log in the futre
    """
    current_events = Event.query.filter(
        Event.date >= datetime.datetime.now() - datetime.timedelta(hours=36)).all()
    return render_template('events_template.html', events=current_events, user=current_user)


@main_blueprint.route('/event/<event_index>')
def event_page(event_index):
    """
    Event page
    event_index: the index of the event that is wanted.
    """
    try:
        event = Event.query.get(event_index)
    except:  # the event doesn't exist
        redirect(url_for('main.events_page'))

    return render_template('event_template.html', event=event, user=current_user)


@main_blueprint.route('/create-event', methods=['GET', 'POST'])
@login_required
@requires_auth_key
def create_event_page():
    """
    Create event page. Used for verified users to create events.
    """
    try:
        if not session["organization"]:
            session["organization"] = current_user.organizations[0].id
    except KeyError as e:
        session["organization"] = current_user.organizations[0].id

    if request.method == 'GET':
        destinations = Destination.query.all()
        message = request.args.get('message')
        if message is None:
            message = 'Create an Event'
        return render_template('create_event_template.html', message=message, user=current_user,
                               destinations=destinations, organization=session["organization"])

    if request.method == 'POST':
        # getting the event info from the form
        # getting the matching build type
        matching_build_type = 0
        needs_matching_build_to = bool(request.form.get('needsmatchingbuildto', False))
        needs_matching_build_from = bool(request.form.get('needsmatchingbuildfrom', False))
        if needs_matching_build_to and needs_matching_build_from:
            matching_build_type = 3
        elif needs_matching_build_to:
            matching_build_type = 1
        elif needs_matching_build_from:
            matching_build_type = 2

        event_info = {
            'name': request.form['eventname'],
            'date': datetime.datetime.strptime(request.form['eventdate'], '%Y-%m-%d'),
            'start_time': datetime.datetime.strptime(request.form['eventstarttime'], '%H:%M'),
            'end_time': datetime.datetime.strptime(request.form['eventendtime'], '%H:%M'),
            'description': request.form['eventdescription'],
            'creator_id': current_user.id,
            'destination_id': Destination.query.filter_by(name=request.form['eventAddress']).one().id,
            'needs_matching_build_to': needs_matching_build_to,
            'needs_matching_build_from': needs_matching_build_from,
            'matching_build_type': matching_build_type,
            'organization_id': request.form['organization']
        }

        try:
            new_event = Event(**event_info)
            db.session.add(new_event)

            db.session.commit()
            logger.info(
                f'New event added to database: {new_event} with carpools: {new_event.carpools}')

        except Exception as e:  # i don't really know how this happens but its good to have
            logger.debug(e)
            return redirect(
                url_for("main.create_event_page", message='Something went wrong. Make sure that all inputs are valid.'))

        flash("Your event, {}, was created successfully!".format(event_info["name"]), "success")
        return redirect(url_for('main.events_page'))
    else:
        return render_template('error_template.html', main_message='Go Away', sub_message='You should not be here.',
                               user=current_user)


@main_blueprint.route('/driver-signup/<carpool_index>', methods=['GET', 'POST'])
@driver_required
@requires_auth_key
def driver_carpool_signup_page(carpool_index):
    """
    Page that drivers go to when they are signing up for a carpool. Still needs a check for sign in
    :carpool_index index of the carpool to be signed up for
    """
    if request.method == 'GET':
        if current_user.is_authenticated:
            carpool = Carpool.query.get(carpool_index)
            if carpool.driver is not None:
                logger.info(f"Carpool {carpool} already has a driver")
                return redirect(url_for('main.event_page', event_index=carpool.event_index))
            carpool.driver = current_user
            carpool.num_passengers = current_user.num_seats
            carpool.driver_index = current_user.id
            db.session.commit()
            logger.info(f'{current_user} signed up for carpool {carpool}')
            # messaging the passengers in region that requested a carpool
            for passenger in [passenger for passenger in carpool.event.passengers_needing_ride if
                              passenger.region_name == carpool.region_name]:
                if passenger.region_name == carpool.region_name:
                    tasks_.send_async_email.delay(
                        passenger.email_address,
                        'Carpool Request',
                        f'Hi {passenger.first_name.capitalize()},\n\nYour request for a carpool has been fulfilled! Check the events page to sign up.\n\nThanks,\nCarpool Manager.'
                    )
            # removing the passengers needing a ride in the region
            for passenger in [passenger for passenger in carpool.event.passengers_needing_ride if

carpooling/templates/bases/webflow_base.html
<!DOCTYPE html>
<!-- This site was created in Webflow. https://www.webflow.com -->
<!-- Last Published: Wed Oct 05 2022 17:13:44 GMT+0000 (Coordinated Universal Time) -->
<html data-wf-domain="sarahs-dandy-site.webflow.io" data-wf-page="633db6b20fc68522b30e41f4"
    data-wf-site="633db6b20fc685cfcc0e41e2">



<head>
    <meta charset="utf-8" />
    <title>{{title}}</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="Webflow" name="generator" />
    <link href="{{ url_for('static', filename='events_style.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename='carrdstyle.css')}}" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans:wght@300&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.26/webfont.js" type="text/javascript"></script>
    <script type="text/javascript">
        WebFont.load({
            google: {
                families: ["Poppins:100,200,300,regular,500,600,700,800,900", "Playfair Display:regular,italic,700,700italic,900,900italic"]
            }
        });
    </script>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,200,0,0" />

    <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js" type="text/javascript"></script><![endif]-->
    <script type="text/javascript">
        !function (o, c) {
            var n = c.documentElement,
                t = " w-mod-";
            n.className += t + "js",
                ("ontouchstart" in o || o.DocumentTouch && c instanceof DocumentTouch) && (n.className += t + "touch")
        }(window, document);
    </script>
    <link href="https://uploads-ssl.webflow.com/633db6b20fc685cfcc0e41e2/633db6b20fc685264c0e421e_q2.jpg"
        rel="shortcut icon" type="image/x-icon" />
    <link href="https://uploads-ssl.webflow.com/633db6b20fc685cfcc0e41e2/633db6b20fc685d03d0e421d_q.jpg"
        rel="apple-touch-icon" />
    <script type="text/javascript">
        window.__WEBFLOW_CURRENCY_SETTINGS = {
            "currencyCode": "USD",
            "$init": true,
            "symbol": "$",
            "decimal": ".",
            "fractionDigits": 2,
            "group": ",",
            "hideDecimalForWholeNumbers": false
        };
    </script>
    {% block styles %}{%endblock%}
</head>

<body class="body">
    <div class="page-content">
        <div class="topnav">
            <a class="{{ 'active' if active_page == 'home' else '' }}" href="{{ url_for('main.home_page') }}">Home</a>
            <a class = "{{ 'active' if active_page == 'events' else '' }}" href="{{ url_for('main.events_page') }}">Events</a>
            {% if user.is_authenticated %}
            <a class="{{ 'active user-info' if active_page == 'user_profile' else 'user-info' }}"
                href="{{ url_for('auth.user_profile_page', user_id=user.id) }}">{{ user.first_name.capitalize() }}
                {{user.last_name.capitalize()}}</a>
            <a class="{{ 'active user-info' if active_page == 'logout' else 'user-info' }}"
                onclick="confirm_logout(event)" href="{{ url_for('main.home_page', logout=True) }}">Logout</a>
            <a class="{{ 'active user-info' if active_page == 'carpools' else 'user-info' }}"
                href="{{url_for('main.manage_carpools_page')}}">Manage Carpools </a>
            {% else %}
            <a class="{{ 'active user-info' if active_page == 'login' else 'user-info' }}"
                href="{{ url_for('auth.login_page') }}">Login</a>
            <a class="{{ 'active user-info' if active_page == 'register' else 'user-info' }}"
                href="{{url_for('auth.generic_register_page')}}">Register/Update</a>
            <a class="{{ 'active user-info' if active_page == 'login_help' else 'user-info' }}"
                href="{{url_for('auth.login_help_page')}}">Login Help</a>

            {% endif %}
        </div>
    </div>
    <div class="banner">
        <div class="banner-second">
            <div class="container center w-container">
                <div class="align-center">
                    <h1 class="style1">
                        {{title}}
                    </h1>

                    <h2 class="style2">{% block subtitle %}{% endblock %}</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="wf-section">

    </div>
    </div> <!-- TODO make a multiline dialog box-->
    <div class="style1">
        {% block main %}{% endblock %}
    </div>
    <!--[if lte IE 9]><script src="//cdnjs.cloudflare.com/ajax/libs/placeholders/3.0.2/placeholders.min.js"></script><![endif]-->
    {% block scripts %}{% endblock %}
    <script>
        function confirm_logout(e) {

            if (!confirm("Are you sure you want to logout?")) {
                e.preventDefault();
            }
        }
    </script>
</body>

</html>