carpooling/routes/admin_routes.py
from carpooling.models import CarpoolSolution, Organization, User, Event
from carpooling.utils import admin_required
from flask import render_template, Blueprint, session, request
from flask_login import current_user
import logging
from carpooling import db

admin_blueprint = Blueprint('admin', __name__, template_folder='templates')
logger = logging.getLogger(__name__)


@admin_blueprint.route('/valid-auth-keys')
@admin_required
def valid_auth_keys_page():
    """
    This page is only accessible if the admin has logged in.
    Page for admins to see all valid auth keys and when they were created.
    """
    pass
#     # querying the auth keys and ordering them
#     auth_keys = AuthKey.query.order_by(AuthKey.date_created).all()

#     # i love naming things
#     return_list = [item.key for item in auth_keys]
#     return_list_2 = [item.date_created for item in auth_keys]
#     return render_template('valid_auth_keys_template.html', return_list=zip(return_list, return_list_2), user=current_user)


@admin_blueprint.route('/admin')
@admin_required
def admin_home_page():
    """
    Page that allows for creation of events, creation of regions, and viewing of the valid authorization keys
    """
    return render_template('admin_home_template.html', user=current_user)


@admin_blueprint.route('/manage-users')
@admin_required
def manage_users_page():
    """
    Admin page that allows for the management of users
    """
    return render_template('manage_users_template.html', users=Organization.query.get(session['organization']).users, user=current_user )

@admin_blueprint.route('/view-routes/<solution_id>')
@admin_required
def route_summary_page(solution_id):
    """
    Function to view the routes
    :param solution_id: the id of the solution to see
    """
    solution = CarpoolSolution.query.get(solution_id)
    generated_carpools = solution.generated_carpools
    event = solution.event
    all_solutions = sorted(event.generated_carpools, key=lambda f: f.id)
    # there is definitely a better way but im lazy
    for i, solution_ in enumerate(all_solutions):
        if solution_.id == solution.id:
            try:
                previous_solution_id = all_solutions[i-1].id
                next_solution_id = all_solutions[i+1].id
            except IndexError as e:
                logger.debug(e)
                if len(all_solutions) > i:
                    previous_solution_id = all_solutions[i-1].id
                    next_solution_id = all_solutions[0].id
                if i == 0:  # its a big lower
                    previous_solution_id = all_solutions[-1].id
                    next_solution_id = all_solutions[i+1].id
    
    logger.debug(f'{previous_solution_id} {next_solution_id}')
    return render_template('route_summary_template.html', event=event, user=current_user, carpool_solution=solution, generated_carpools=generated_carpools, next_solution_id=next_solution_id, previous_solution_id=previous_solution_id)

@admin_blueprint.route('/manage-organization')
@admin_required
def manage_organization_page():
    organization = Organization.query.get(int(session['organization']))
    return render_template('manage_organization_template.html', user=current_user, organization=organization)

@admin_blueprint.route('/edit-organization', methods=['GET', 'POST'])
@admin_required
def edit_organization_page():
    if request.method == 'GET':
        organization = Organization.query.get(int(session['organization']))
        return render_template('edit_organization_template.html', user=current_user, organization=organization)
    elif request.method == 'POST':
        organization = Organization.query.get(int(session['organization']))
        organization.name = request.form['organizationname']
        organization.description = request.form['organizationdescription']
        db.session.commit()
        return render_template('manage_organization_template.html', user=current_user, organization=organization)

carpooling/routes/auth_routes.py
"""
All routes that have to do with authorization are defined here.
"""

from carpooling import db, mail
from carpooling.models import Address, User
import logging
from carpooling.tasks import send_async_email
from carpooling.utils import PersonAlreadyExistsException, InvalidNumberOfSeatsException
from flask import render_template, request, redirect, url_for, make_response, flash, Blueprint, current_app
import secrets
import datetime
from flask_login import login_required, current_user, login_user
from werkzeug.security import check_password_hash, generate_password_hash
from itsdangerous import URLSafeSerializer
from flask_mail import Message

auth_blueprint = Blueprint('auth', __name__, template_folder='templates')
logger = logging.getLogger(__name__)


@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login_page():
    """
    Login page for drivers and passengers.
    """
    if request.method == 'GET':
        return render_template('login_template.html', message='Login!', user=current_user)
    if request.method == 'POST':
        user = User.query.filter_by(email_address=request.form['email']).first()
        if user is None:
            logger.debug('attempted user does not exist')
            return render_template('login_template.html', message='That user does not exist. Please try again.',
                                   user=current_user)
        if user.password is None:
            logger.debug('attempted user is probably a legacy driver')
            return render_template('error_template.html', main_message='Not registered',
                                   sub_message='The user exists in the database but is not registered to a user. Please use update/register.',
                                   user=current_user)

        if check_password_hash(user.password, request.form['password']):
            try:
                remember = request.form.get('remember')
            except ValueError:
                remember = False
            login_user(user, remember=True)
            flash("Logged in successfully!", "success")
            return redirect(url_for('main.home_page'))
        else:
            return render_template('login_template.html', message='Incorrect password. Please try again.',
                                   user=current_user)


@auth_blueprint.route('/reset-password/<user_id>/<token>', methods=['GET', 'POST'])
def reset_password_page(user_id, token):
    """
    Page that allows for the resetting of a password
    user_id: the id of the user that is resetting their password
    token: the token that is used to verify that the user is who they say they are
    """
    if request.method == 'GET':
        user = User.query.filter_by(id=user_id).first()
        if user and user.verify_reset_password_token(token):
            return render_template('reset_password_template.html', user=current_user, user_id=user_id, token=token)
        else:
            return render_template('error_template.html', main_message='Go Away', sub_message='You should not be here.',
                                   user=current_user)
    if request.method == 'POST':
        user = User.query.filter_by(id=user_id).first()
        if user and user.verify_reset_password_token(token):
            if request.form['password'] == request.form['confirmpassword']:
                user.password = generate_password_hash(request.form['password'], method='sha256')
                db.session.commit()
                logger.info('Password reset for user {}'.format(user))
                return redirect(url_for('auth.login_page'))
            else:
                return render_template('reset_password_template.html',
                                       message='Passwords do not match. Please try again.', user=current_user,
                                       user_id=user_id, token=token)
        else:
            return render_template('error_template.html', main_message='Go Away', sub_message='You should not be here.',
                                   user=current_user)


# @auth_blueprint.route('/verify_auth_key/<next>/<kwargs_keys>/<kwargs_string>', methods=['GET', 'POST'])
# def verify_auth_key_page(next, kwargs_keys, kwargs_string):
#     """
#     Page that users are redirected to if they need to get an auth key
#     next: the next page to go to
#     kwargs_keys: the keys of the kwargs, encoded by the decorator
#     kwargs_string: the values of the kwargs, encoded by the decorator

#     This page is called by the decorator requires_auth_key, and is pretty much exclusivelt used for that purpose.

#     """
#     if request.method == 'GET':
#         # this is how the things are encoded
#         # kwargs_keys = '--'.join(kwargs)
#         # kwargs_string = '--'.join([kwargs[kwarg] for kwarg in kwargs])
#         return render_template('get_driver_access_template.html', next=next, kwargs_keys=kwargs_keys,
#                                kwargs_string=kwargs_string, user=current_user)
#     if request.method == 'POST':
#         try:
#             has_key = request.form['key'] == AuthKey.query.order_by(AuthKey.index.desc()).first().key or request.form['key'] == \
#                     AuthKey.query.order_by(AuthKey.index.desc()).all()[1].key
#         except IndexError:
#             has_key = request.form['key'] == AuthKey.query.order_by(AuthKey.index.desc()).first().key

#         if has_key:
#             if current_user.is_authenticated:
#                 current_user.team_auth_key = AuthKey.query.order_by(AuthKey.index.desc()).first().key
#                 db.session.commit()
#                 logger.info('Driver access granted to user {}'.format(current_user))

#             # re-encoding the keys
#             kwargs = {}
#             for kwarg_key, kwarg in zip(kwargs_keys.split('--'), kwargs_string.split('--')):
#                 kwargs[kwarg_key] = kwarg

#             # setting the response
#             response = make_response(redirect(url_for(next, **kwargs)))
#             s = URLSafeSerializer(current_app.secret_key)
#             logger.info('setting cookie')
#             response.set_cookie('driver-access', s.dumps(['access granted']),
#                                 max_age=datetime.timedelta(seconds=60))
#             return response
#         else:
#             flash('Invalid Auth Key')  # theres no flash support but like whatever
#             return render_template('get_driver_access_template.html', next=next, kwargs_keys=kwargs_keys,
#                                    kwargs_string=kwargs_string, user=current_user, message='Invalid Key')


@auth_blueprint.route('/update-user', methods=['GET', 'POST'])
@login_required
def update_user_information_page():
    """
    Page that allows for the updating of user information -- basically just a copy of the sign up page but with default values
    """
    if (request.method == 'GET') and (current_user.num_seats is not None):
        return render_template('update_user_information_template.html', user=current_user)
    elif request.method == 'GET':
        logger.debug(current_user)
        return render_template('update_user_information_template_passenger.html', user=current_user)
    elif request.method == 'POST':
        # if the user is a driver
        if current_user.num_seats is not None:
            try:
                logger.info(request.form)
                current_user.addresses[0].address_line_1 = request.form['addressline1']
                current_user.addresses[0].address_line_2 = request.form['addressline2']
                current_user.addresses[0].city = request.form['city']
                current_user.addresses[0].zip_code = request.form['zipcode']
                current_user.addresses[0].latitude = request.form['latitude']
                current_user.addresses[0].longitude = request.form['longitude']
                current_user.addresses[0].code = request.form['place_id']
                current_user.first_name = request.form['firstname'].lower()
                current_user.last_name = request.form['lastname'].lower()
                current_user.email_address = request.form['email']
                current_user.phone_number = request.form['phonenumber']
                current_user.extra_information = request.form['note']
                current_user.car_type_1 = request.form['cartype1']
                current_user.car_color_1 = request.form['carcolor1']
                current_user.car_type_2 = request.form['cartype2']
                current_user.car_color_2 = request.form['carcolor2']
                current_user.emergency_contact_number = request.form['emergencycontact']
                current_user.emergency_contact_relation = request.form['emergencycontactrelation']
                current_user.num_seats = request.form['numberofseats']
                current_user.num_years_with_license = request.form['licenseyears']
                current_user.student_or_parent = request.form['studentorparent']
                db.session.commit()
                return redirect(url_for('auth.user_profile_page'))
            except Exception as e:
                logger.debug(e)
                flash("There was an error. Please make sure that your information is valid and try again.")
                return render_template('update_user_information_template.html', message='There was an error',
                                       user=current_user)
        # if the user is a passenger
        else:
            try:
                current_user.addresses[0].address_line_1 = request.form['addressline1']
                current_user.addresses[0].address_line_2 = request.form['addressline2']
                current_user.addresses[0].city = request.form['city']
                current_user.addresses[0].zip_code = request.form['zipcode']
                current_user.addresses[0].latitude = request.form['latitude']
                current_user.addresses[0].longitude = request.form['longitude']

carpooling/templates/edit_organization_template.html
{% extends 'bases/bootstrap_base.html' %}

{% set active_page='user_profile' %}

{% block title %}Edit Organization{% endblock %}

{% block main %}
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBghXgyj-zW3xh5e-2ryMGNh1iRCKvRG6k&libraries=places"
            xmlns="http://www.w3.org/1999/html"></script>
<section class="position-relative py-4 py-xl-5">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <h1 style="font-family: Bungee Shade;font-size: 57.928px;color: var(--bs-link-color);">Change Organization Details</h1>
                <p class="w-lg-50">It's okay to have a style shift.</p>
            </div>
        </div>
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 col-xl-4">
                <div class="card mb-5">
                    <div class="card-body d-flex flex-column align-items-center">
                        <div class="bs-icon-xl bs-icon-circle bs-icon-primary bs-icon my-4"><svg class="bi bi-shuffle" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M0 3.5A.5.5 0 0 1 .5 3H1c2.202 0 3.827 1.24 4.874 2.418.49.552.865 1.102 1.126 1.532.26-.43.636-.98 1.126-1.532C9.173 4.24 10.798 3 13 3v1c-1.798 0-3.173 1.01-4.126 2.082A9.624 9.624 0 0 0 7.556 8a9.624 9.624 0 0 0 1.317 1.918C9.828 10.99 11.204 12 13 12v1c-2.202 0-3.827-1.24-4.874-2.418A10.595 10.595 0 0 1 7 9.05c-.26.43-.636.98-1.126 1.532C4.827 11.76 3.202 13 1 13H.5a.5.5 0 0 1 0-1H1c1.798 0 3.173-1.01 4.126-2.082A9.624 9.624 0 0 0 6.444 8a9.624 9.624 0 0 0-1.317-1.918C4.172 5.01 2.796 4 1 4H.5a.5.5 0 0 1-.5-.5z"></path>
                                <path d="M13 5.466V1.534a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384l-2.36 1.966a.25.25 0 0 1-.41-.192zm0 9v-3.932a.25.25 0 0 1 .41-.192l2.36 1.966c.12.1.12.284 0 .384l-2.36 1.966a.25.25 0 0 1-.41-.192z"></path>
                            </svg></div>
                        <form class="text-center" action="{{ url_for('admin.edit_organization_page') }}" method="post">
                            <div class="text-start mb-3"><small class="form-text text-start">Organization Name</small><input class="form-control" type="text" name="organizationname" value="{{ organization.name }}" placeholder="Organization Name"/></div>
                            <div class="text-start mb-3"><small class="form-text text-start">Organization Description</small><textarea class="form-control" type="text" name="organizationdescription" placeholder="Description">{{ organization.description }}</textarea></div>
                            <div class="mb-3"><button class="btn btn-primary d-block w-100" type="submit">Update</button></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}


{%  block scripts %}

<script>

    let autocomplete = google.maps.places.Autocomplete;
    let addressLine1Field = document.getElementById("addressline1");
    let addressLine2Field = document.getElementById("addressline2");
    let zipCodeField = document.getElementById("zipcode");
    let cityField = document.getElementById("city");

    let latitude; // making these global so we can use them in the submit function without having to be in the form
    let longitude;
    let place_id;

    initAutocomplete()

    function initAutocomplete() {
        console.log("initAutocomplete")


      // Create the autocomplete object, restricting the search predictions to
      // addresses in the US
      autocomplete = new google.maps.places.Autocomplete(addressLine1Field, {
        componentRestrictions: { country: ["us"] },
        fields: ["address_components", "geometry", "place_id"],
        types: ["address"],
      });

      addressLine1Field.focus();
      console.log("autocomplete initialized")

      // When the user selects an address from the drop-down, populate the
      // address fields in the form.
      autocomplete.addListener("place_changed", fillInAddress);
    }

    function fillInAddress() {
        // Get the place details from the autocomplete object.
        const place = autocomplete.getPlace();
        let address1 = "";
        let postcode = "";
        let city = ""

        // Get each component of the address from the place details,
        // and then fill-in the corresponding field on the form.
        // place.address_components are google.maps.GeocoderAddressComponent objects
        // which are documented at http://goo.gle/3l5i5Mr
        console.log(place.address_components)
        for (var i = 0; i < place.address_components.length; i++) {
          // @ts-ignore remove once typings fixed
          let component = place.address_components[i];
          const componentType = component.types[0];


          switch (componentType) {
            case "street_number": {
              address1 = `${component.long_name} ${address1}`;
              break;
            }
            case "route": {
              address1 += component.short_name;
              break;
            }
            case "locality": {
                city = component.long_name;
                break;
            }
            case "postal_code": {
              postcode = `${component.long_name}${postcode}`;
              break;
            }
          }
        }

        addressLine1Field.value = address1;
        zipCodeField.value = postcode;
        cityField.value = city;
        latitude = place.geometry.location.lat();
        longitude = place.geometry.location.lng();
        place_id = place.place_id;
        console.log(latitude, longitude)
        console.log(place_id)
        document.getElementById("addressline2").focus() // focusing the cursor on address line 2
      }

    function verify_and_submit_form(event) {
        // this function is called when the submit button is clicked
        // it verifies that the passwords match and then submits the form
        let password = document.getElementById("password").value;
        let confirmpassword = document.getElementById("confirmpassword").value;
        if (password != confirmpassword) {
            alert("Passwords do not match");
            event.preventDefault();
            return false;
        }
        else {
            event.preventDefault();
            console.log(latitude, longitude)
            document.getElementById("latitude").value = latitude;
            document.getElementById("longitude").value = longitude;
            document.getElementById("place_id").value = place_id;
            document.getElementById("registerform").submit();
        }
    }
</script>
{% endblock %}

carpooling/templates/error_template.html
{% extends 'bases/bootstrap_base.html' %}

{% set active_page='home' %}

{% block title %}{{main_message}}{% endblock %}

{% block main %}
<h1 id="text01" class="style1">{{main_message}}</h1>
<hr id="divider02" class="style1">
<div id="text02" class="card">
    <p class="card-body">
        {{sub_message}}
    </p>
</div>
<ul id="buttons01" class="style1 buttons">
    <li>
        <a href="{{url_for('main.home_page')}}" class="button n01">
            <span class="label">Return Home</span>
        </a>
    </li>
</ul>
{% endblock %}

carpooling/templates/route_summary_template.html
{% extends 'bases/carrd_base.html' %}


{% block title %}Carpools for Event {% endblock %}

{% block styles %}
<style>
    #detailsdiv {
        display: block;
        position: absolute;
        top: 20%;
        left: 90%;
        width: 40%;
        height: inherit;
        background-color: #888;
        border-radius: 3%;
        box-shadow: 0px 0px 5px 0px rgba(255, 225, 225, 0.75);
        padding: 10px;
        margin: 10px;
        z-index: 1;
    }

    .hiddendetails {
        display: none;
        max-height: 0;
    }

    span.style2 {
        color: white;
        font-family: 'Fira Sans', sans-serif;
        font-size: small;
        padding-top: 3px;
        padding-bottom: 3px;
        display: block;
        margin-top: 3px;
    }

    .visibledetails:hover {
        background-color: #AAA;
        transition: none;
        cursor: pointer;
    }

    .visibledetails:hover .active {
        background-color: #888;
        transition: none;
        cursor: pointer;
        transition: scale(1.1);
    }

    .hiddendetails.active {
        background-color: #999;
        display: block;
        height: max-content;
        max-height: max-content;
    }

    #mapdiv {
        position: relative;
        height: 700px;
        width: 100%;
        border-color: #fff;
        background-color: #fff;
    }

    .buttondiv {
        display: inline-block;
    }
</style>
{% endblock %}
{% block main %}
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD_JtvDeZqiy9sxCKqfggODYMhuaeeLjXI&callback=initMap"
    async="false"></script>

<h1 class="style1"> Route 1 </h1>
<div id="mapdiv"></div>
<!--- This is where the map will be rendered-->
<div id="detailsdiv">
    {% for carpool in generated_carpools %}
    <div id="carpool{{carpool.id}}">
        <div class="visibledetails details{{carpool.id}}" onclick="renderMap(event, '{{carpool.id}}')">
            {%  if carpool_solution.type == 'to' %}
            <p class="style2">{{carpool.from_address.users[0].first_name}}'s Home to
                {{carpool.to_address.destination.name}}</p>
            {%  elif carpool_solution.type == 'from' %}
            <p class="style2">{{carpool.from_address.destination.name}}'s Home to
                {{carpool.to_address.users[0].first_name}}</p>
            {%  endif %}

        </div>
        <div class="hiddendetails details{{carpool.id}}">
            {% for part in carpool.generated_carpool_parts %}
            <span class="style2" class="partshowing">
                {{part.from_address.address_line_1}} to {{part.to_address.address_line_1}}
            </span>
            <br>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</div>
<div class="buttondiv">
    <ul class="style1 buttons">
        <li>
            <a class="button n01" id="leftbutton"
                href="{{url_for('admin.route_summary_page', solution_id=previous_solution_id)}}"><svg>
                    <use xlink:href="#icon-b64"></use>
                </svg>
                <span class="label"> Previous Solution</span>
            </a>

            <a class="button n01" id="rightbutton"
                href="{{url_for('admin.route_summary_page', solution_id=previous_solution_id)}}"><svg>
                    <use xlink:href="#icon-b64"></use>
                </svg>
                <span class="label">
                    Next Solution
                </span>
            </a>
        </li>
    </ul>
</div>
{% endblock %}

{% block scripts %}


<script>
    console.log("starting script");
    var map = "";
    let rendered_carpool;



    window.initMap = initMap

    function initMap() {
        window.directionsService = new google.maps.DirectionsService();
        window.directionsRenderer = new google.maps.DirectionsRenderer();

        map = new google.maps.Map(document.getElementById("mapdiv"), {
            zoom: 6,
            center: { lat: 41.85, lng: -87.65 },
        });
        directionsRenderer.setMap(map);
        document.getElementById("submit").addEventListener("click", () => {
            calculateAndDisplayRoute(directionsService, directionsRenderer);
        });
        console.log("map initialized");
    }

    function calculateAndDisplayRoute(directionsService, directionsRenderer) {
        //const waypts = [];
        //const checkboxArray = document.getElementById("waypoints");
        //
        //for (let i = 0; i < checkboxArray.length; i++) {
        //    if (checkboxArray.options[i].selected) {
        //        waypts.push({
        //            location: checkboxArray[i].value,
        //            stopover: true,
        //        });
        //    }
        //}


        directionsService
            .route({
                origin: 'Richmond, VA',
                destination: 'Chicago, IL',
                //waypoints: waypts,
                //optimizeWaypoints: true,
                travelMode: google.maps.TravelMode.DRIVING,
            })
            .then((response) => {
                directionsRenderer.setDirections(response);
                console.log('test request successful');

                const route = response.routes[0];
                //const summaryPanel = document.getElementById("directions-panel");
                //
                //summaryPanel.innerHTML = "";
                //
                //// For each route, display summary information.
                //for (let i = 0; i < route.legs.length; i++) {
                //    const routeSegment = i + 1;
                //
                //    summaryPanel.innerHTML +=
                //        "<b>Route Segment: " + routeSegment + "</b><br>";
                //    summaryPanel.innerHTML += route.legs[i].start_address + " to ";
                //    summaryPanel.innerHTML += route.legs[i].end_address + "<br>";
                //    summaryPanel.innerHTML += route.legs[i].distance.text + "<br><br>";
                //}
            })
            .catch((e) => window.alert("Directions request failed due to " + status + e));
    }

    function renderMap(event, carpool_id) {

        //toggling the visibility
        const detailsdiv = document.getElementById('carpool' + carpool_id);
        const hiddendetails = detailsdiv.children[1];
        const visibledetails = detailsdiv.children[0];
        for (let i = 0; i < document.getElementById('detailsdiv').children.length; i++) {
            document.getElementById('detailsdiv').children[i].children[1].classList.remove('active')
            document.getElementById('detailsdiv').children[i].children[0].classList.remove('active')
        }
        if (hiddendetails.classList.contains("active")) {
            hiddendetails.classList.remove("active");
            visibledetails.classList.remove("active");
            console.log('deactivated the details div')
        } else {
            console.log('activated the details div.')
            hiddendetails.classList.add("active");
            visibledetails.classList.add("active");
        }



        // getting data for map
        let http_request = new XMLHttpRequest();
        window.directionsRenderer.setDirections({ routes: [] });

        console.log('recieved request to render map');
        http_request.open("GET", "{{url_for('internal.get_generated_carpool_data', carpool_id='CHANGETHIS')}}".replace('CHANGETHIS', carpool_id), true);
        http_request.send();
        http_request.onreadystatechange = function () {
            if (this.readyState == 4 && this.status == 200) {
                let data = JSON.parse(this.responseText);
                console.log(data);

                directionsService
                    .route({
                        origin: data.origin,
                        destination: data.destination,
                        waypoints: data.waypoints,
                        optimizeWaypoints: false,
                        travelMode: google.maps.TravelMode.DRIVING,
                    })
                    .then((response) => {
                        directionsRenderer.setDirections(response);
                        console.log('request was successful for map render')
                        const route = response.routes[0];


                    })
                //const summaryPanel = document.getElementById("directions-panel");

                rendered_carpool = carpool_id; // this is the carpool that is currently rendered
            }

            //function render_map() {
            //    const mapdiv = document.getElementById("mapdiv");
            //    const map = new google.maps.Map(mapdiv, {
            //        zoom: 6,
            //        center: { lat: 41.85, lng: -87.65 },
            //    });
            //    directionsRenderer.setMap(map);
            //}


            //window.initMap = initMap;
        }
    }

</script>


{% endblock %}

carpooling/templates/view_organization_template.html
{% extends 'bases/bootstrap_base.html' %}

{% block title %}{{ organization.name }}{% endblock %}

{% block main %}
        <section class="position-relative py-4 py-xl-5" style="background: linear-gradient(180deg, var(--bs-gray-200) 0%, var(--bs-gray-400) 100%); height: 80vh">
<h1 id="text02" class="text-center" style="opacity: 1; transform: none; color: var(--bs-primary); font-family: 'Bungee Shade', sans-serif">{{organization.name}}</h1>
<p id="text07" class="text-center" style="opacity: 1; transform: none;"></p>
                <div class="row d-flex justify-content-center text-center">
                <div class="col-md-6 col-xl-4">
<div class="card">
<div class="card-body shadow d-flex flex-column align-items-center">
<h5 class="card-title">Organization Details</h5>
    {% if organization.description %}
    {{ organization.description }} <br><br>
{% endif %}
    Number of members: {{ organization.users | length }} <br>

<a class="btn btn-outline-dark" href="{{ url_for("main.add_new_organization_page") }}">Add another organization</a>
</div>
</div></div>
</div>
    </section>
{% endblock %}